name: "AutoCoder"
description: "Automatically generate code from GitHub issues using OpenAI's ChatGPT and create a pull request with the results."
author: "Your Name or Organization"

branding:
  icon: "robot"
  color: "blue"

inputs:
  github_token:
    description: "Personal access token used for GitHub API authentication."
    required: true
  openai_api_key:
    description: "API key for OpenAI to generate code based on issue descriptions."
    required: true
  repository:
    description: "Repository in the format owner/repo where code will be generated."
    required: true
  issue_number:
    description: "The issue number that triggered the action."
    required: true
  script_path:
    description: "Path to the shell script that interacts with ChatGPT."
    required: true
    default: "./scripts/script.sh"
  label:
    description: "The label that triggers code generation."
    required: true
    default: "autocoder-bot"

outputs:
  pull_request_url:
    description: "URL of the pull request created by the action."

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Ensure script is executable"
      run: chmod +x ${{ inputs.script_path }}

    - name: "Run AutoCoder Script"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REPOSITORY: ${{ inputs.repository }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
      run: ${{ inputs.script_path }} "$GITHUB_TOKEN" "${{ inputs.repository }}" "${{ inputs.issue_number }}" "${{ inputs.openai_api_key }}"

    - name: "Upload generated code artifact"
      uses: actions/upload-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: "Download artifact"
      uses: actions/download-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-artifact/

    - name: "Prepare generated code"
      run: |
        mkdir -p autocoder-generated
        cp -R autocoder-artifact/* autocoder-generated/
        echo "// Force change: $(date)" > autocoder-generated/force_change.txt

    - name: "Configure Git user"
      run: |
        git config --global user.name "autocoder-bot"
        git config --global user.email "actions@github.com"

    - name: "Commit and push changes"
      run: |
        git checkout -B autocoder-branch-${{ inputs.issue_number }}
        git add autocoder-generated
        git commit --author="autocoder-bot <actions@github.com>" -m "Autocoder generated code for issue #${{ inputs.issue_number }}"
        git push -f origin autocoder-branch-${{ inputs.issue_number }}

    - name: "Create Pull Request"
      id: pr
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Autocoder generated code for issue #${{ inputs.issue_number }}"
        branch: "autocoder-branch-${{ inputs.issue_number }}"
        base: main
        labels: ${{ inputs.label }}
        author: "autocoder-bot <actions@github.com>"
        committer: "autocoder-bot <actions@github.com>"

    - name: "Set output PR URL"
      run: echo "pull_request_url=${{ steps.pr.outputs.pull-request-url }}" >> $GITHUB_OUTPUT