name: Auto_Coder

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List Repo Contents
        run: ls -R

      - name: Make script executable
        run: chmod +x ./scripts/script.sh
      
      - name: Run AutoCoder Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh "$GITHUB_TOKEN" "$REPOSITORY" "$ISSUE_NUMBER" "$OPENAI_API_KEY"

      - name: Upload Generated Code as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/
      
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: List Artifact Contents
        run: ls -R autocoder-artifact/

      # Instead of copying to the root directory, copy to a dedicated folder so that the diff is clear.
      - name: Copy Generated Code to a dedicated folder
        run: |
          mkdir -p autocoder-generated
          cp -R autocoder-artifact/* autocoder-generated/

      - name: Debug - List Copied Files in autocoder-generated
        run: ls -R autocoder-generated

      # Insert a file into the dedicated folder with current timestamp to force a change.
      - name: Force a change for PR detection
        run: |
          echo "// Force change: $(date)" > autocoder-generated/force_change.txt

      - name: Configure Git
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Debug Git Status Before Commit
        run: |
          git status

      - name: Commit Generated Code
        run: |
          # Create or update the branch with a forced reset
          git checkout -B autocoder-branch-${{ github.event.issue.number }}
          # Add only the dedicated folder (and any other changes if needed)
          git add autocoder-generated
          git status
          git commit -m "Autocoder generated code for issue #${{ github.event.issue.number }}"
          git push -f origin autocoder-branch-${{ github.event.issue.number }}
      
      - name: Debug - Final Git Status
        run: git status
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Autocoder generated code for issue #${{ github.event.issue.number }}"
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          labels: autocoder-bot
