#name: Auto_Coder
#
#on:
#  issues:
#    types: [opened, reopened, labeled]
#
#jobs:
#  autocoder:
#    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      pull-requests: write
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      # Run the reusable action to generate files (action still used)
#      - name: Run AutoCoder Reusable Action
#        uses: Huerkan-Utan/AutoCoder@v1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#          REPOSITORY: ${{ github.repository }}
#          ISSUE_NUMBER: ${{ github.event.issue.number }}
#          LABEL: "autocoder-bot"
#
#      # --- The test expects these steps to be present directly in the job ---
#      - name: Configure Git
#        run: |
#          git config --global user.name "autocoder-bot"
#          git config --global user.email "actions@github.com"
#        shell: bash
#
#      - name: Debug Git Status Before Commit
#        run: git status
#        shell: bash
#
#      - name: Commit Generated Code
#        run: |
#          # Create or update the branch
#          git checkout -B autocoder-branch-${{ github.event.issue.number }}
#          # Stage everything in the dedicated folder
#          git add autocoder-generated
#          git status
#          # Commit, explicitly setting the author
#          git commit --author="autocoder-bot <actions@github.com>" -m "Autocoder generated code for issue #${{ github.event.issue.number }}"
#          # Force-push to overwrite any existing branch
#          git push -f origin autocoder-branch-${{ github.event.issue.number }}
#        shell: bash
#
#      - name: Debug - Final Git Status
#        run: git status
#        shell: bash
#
#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          title: "Autocoder generated code for issue #${{ github.event.issue.number }}"
#          branch: autocoder-branch-${{ github.event.issue.number }}
#          base: main
#          labels: autocoder-bot
#          author: "autocoder-bot <actions@github.com>"
#          committer: "autocoder-bot <actions@github.com>"


name: Auto_Coder

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Run AutoCoder reusable action
        id: autocoder
        uses: Huerkan-Utan/AutoCoder@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          SCRIPT_PATH: "./scripts/script.sh"

      - name: Download generated code artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.autocoder.outputs.artifact-name }}
          path: autocoder-artifact/

      - name: Prepare generated code
        run: |
          mkdir -p autocoder-generated
          cp -R autocoder-artifact/* autocoder-generated/
          echo "// Force change: $(date)" > autocoder-generated/force_change.txt
          ls -R autocoder-generated

      - name: Configure Git
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Commit generated code
        run: |
          git checkout -B autocoder-branch-${{ github.event.issue.number }}
          git add autocoder-generated
          git commit --author="autocoder-bot <actions@github.com>" -m "Autocoder generated code for issue #${{ github.event.issue.number}}" || echo "No changes to commit"
          git push -f origin autocoder-branch-${{ github.event.issue.number }}
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Autocoder generated code for issue #${{ github.event.issue.number }}"
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          labels: autocoder-bot
          author: "autocoder-bot <actions@github.com>"
          committer: "autocoder-bot <actions@github.com>"
