name: Auto_Coder

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  autocoder:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Run your reusable action to generate code
      - name: Run AutoCoder Reusable Action
        uses: uses: Huerkan-Utan/AutoCoder@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          LABEL: "autocoder-bot"

      # Configure git for committing changes
      - name: Configure Git
        run: |
          git config --local user.name "autocoder-bot"
          git config --local user.email "actions@github.com"

      # Commit and push the generated code
      - name: Commit and push generated code
        run: |
          git checkout -B autocoder-branch-${{ github.event.issue.number }}
          git add autocoder-generated
          git commit --author="autocoder-bot <actions@github.com>" -m "Autocoder generated code for issue #${{ github.event.issue.number }}"
          git push -f origin autocoder-branch-${{ github.event.issue.number }}

      # Create the pull request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Autocoder generated code for issue #${{ github.event.issue.number }}"
          branch: "autocoder-branch-${{ github.event.issue.number }}"
          base: main
          labels: autocoder-bot
          author: "autocoder-bot <actions@github.com>"
          committer: "autocoder-bot <actions@github.com>"
