name: Auto_Coder

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    #if: >-
    #  github.event.action == 'opened' || 
    #  github.event.action == 'reopened' || 
    #  (github.event.action == 'labeled' && github.event.label.name == 'autocoder-bot')
    #if: ${{ (github.event.action == 'labeled' && github.event.label.name == 'autocoder-bot') || (github.event.issue.labels && contains(github.event.issue.labels.*.name, 'autocoder-bot')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - List Repo Contents
        run: ls -R

      - name: Make script executable
        run: chmod +x ./scripts/script.sh
      
      - name: Run AutoCoder Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh "$GITHUB_TOKEN" "$REPOSITORY" "$ISSUE_NUMBER" "$OPENAI_API_KEY"

      - name: Upload Generated Code as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/
      
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: List Artifact Contents
        run: ls -R autocoder-artifact/
      
      - name: Configure Git
        run: |
          git config --global user.name "autocoder-bot"
          git config --global user.email "actions@github.com"

      - name: Commit Generated Code
        run: |
          git checkout -b autocoder-branch-${{ github.event.issue.number }}
          git add .
          git commit -m "Autocoder generated code for issue #${{ github.event.issue.number }}"
          git push origin autocoder-branch-${{ github.event.issue.number }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          labels: autocoder-bot